### ISSUE TITLE
[Fix]多进程可能导致惊群现象

### ISSUE THREAD

**Issue by NaturalSelect** [wyapx/NullcatServer#2]
https://github.com/wyapx/NullcatServer/blob/25903e1930ea14e62916b930b98faf76eff8ba16/core/server.py#L95

**Comment by wyapx** [comment]
辣你用单核CPU啊

**Comment by NaturalSelect** [comment]
务必寄我一个单核心cpu

**Comment by wyapx** [comment]
> 务必寄我一个单核心cpu

@NaturalSelect 请给我钱

**Comment by NaturalSelect** [comment]
> > 务必寄我一个单核心cpu
> 
> @NaturalSelect 请给我钱

给钱了还叫白嫖吗？
